import { ReactNode } from 'react'
import './globals.css'
import { Inter } from 'next/font/google'
import NavMenu from './components/NavMenu'
import Sidebar from './components/Sidebar'

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })

export const metadata = {
  title: 'Portal Trilogia',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  const isLogged = true

  return (
    <html lang="en">
      <body
        className={`${inter.variable} bg-gray-100 px-7 py-7 font-sans text-zinc-800 md:px-28`}
      >
        {isLogged ? <NavMenu /> : null}
        {isLogged ? <Sidebar /> : null}
        {children}
      </body>
    </html>
  )
}
